### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:53438

### ISSUE THREAD

**Issue by phaze-the-dumb** [SharkFinPro/razer-chroma-nodejs#4]
So i am using the code in the readme

```js
const Chroma = require("razer-chroma-nodejs");
 
// Initialize Chroma
Chroma.util.init(() => {
    console.log("Chroma Editing Started");
 
    // Set the mouse color to green
    Chroma.effects.mouse.setColor(Chroma.colors.GREEN);
 
    // Close Chroma after 5 seconds
    setTimeout(() => {
        Chroma.util.uninit(() => {
            console.log("Chroma Editing Stopped");
        });
    }, 5000);
});
```

But i get this error when i try to use it

```
Error: connect ECONNREFUSED 127.0.0.1:53438
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 53438
}
```

Im not sure if this is just me because i tried to write my own wrapper and i got the exact same error

Please help...

Thanks :D

**Comment by VeqsaGit** [comment]
I got the same error.

**Comment by SharkFinPro** [comment]
Hi, I am looking into this issue and will update you as soon as I figure it out.
It is likely an API change, and if so I will update the repository.

**Comment by Northernside** [comment]
> Hi, I am looking into this issue and will update you as soon as I figure it out. It is likely an API change, and if so I will update the repository.

Any updates?

**Comment by SharkFinPro** [comment]
> > Hi, I am looking into this issue and will update you as soon as I figure it out. It is likely an API change, and if so I will update the repository.
> 
> Any updates?

Not yet,
It appears to be an issue in "src/util/chroma.js" at the createEffect method.
I tested using a different instance of the rest api, and it worked with that, so I'm not entirely sure what it is.

Once I figure it out I'll be sure to update.

**Comment by SharkFinPro** [comment]
Fixed this in the most recent version.
I'm sure there's a better way to do this but it works for now.

Closing this issue unless the bug comes back

**Comment by Northernside** [comment]
Don't know why but this error still happens for me:
```
PS C:\Users\Elias\OneDrive\Projects\Coding\RazerTesting> node index.js
Error: connect ECONNREFUSED ::1:54235
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 54235
```
![image](https://user-images.githubusercontent.com/60970791/147362855-c5461006-d490-4eca-b209-de67d9062a22.png)

**Comment by SharkFinPro** [comment]
It should still say that at first but it should work.

Do the effects for your devices still not turn on?

**Comment by Ledzz** [comment]
I've got the same error, same trying using the code from the readme, but keyboard instead of mouse. 
Upd: it worked after restarting synapse for 5 seconds, and then broke again.

**Comment by Ledzz** [comment]
Oh nvm, it worked after restarting synapse. Thank you!

**Comment by SharkFinPro** [comment]
I just went through and fixed a bunch of things.
This issue should now be fixed for sure, if it is not please let me know!

Check the readme as some things have changed :)

**Comment by Ledzz** [comment]
Hello! Looks like not fixed, when I start script my keyboard's backlight kinda reboots, but It has not the color from script, but the color from my Synapse settings. I'm using v1.3.2

**Comment by SharkFinPro** [comment]
> Hello! Looks like not fixed, when I start script my keyboard's backlight kinda reboots, but It has not the color from script, but the color from my Synapse settings. I'm using v1.3.2

Are you getting any messages when you run it in the console? If attempting to run it a second time does not work make sure that chroma apps are enabled in razer synapse.

**Comment by Ledzz** [comment]
Yes, they're in the console: 
```
Error: connect ECONNREFUSED 127.0.0.1:65402
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 65402
}
```

And yes, Chroma apps are enabled, and I can see an active app in Synapse with `This edits Razer Chroma effects using nodejs` description.
